CREATE TABLE Bolum (
    BolumID INT IDENTITY(1,1) PRIMARY KEY,
    BolumAdi NVARCHAR(100) NOT NULL
);

CREATE TABLE Ogrenci (
    OgrenciID INT IDENTITY(1,1) PRIMARY KEY,
    Ad NVARCHAR(50) NOT NULL,
    Soyad NVARCHAR(50) NOT NULL,
    BolumID INT NOT NULL,
    FOREIGN KEY (BolumID) REFERENCES Bolum(BolumID)
);

CREATE TABLE Ders (
    DersID INT IDENTITY(1,1) PRIMARY KEY,
    DersAdi NVARCHAR(100) NOT NULL,
    Kredi TINYINT NOT NULL
);

CREATE TABLE OgrenciDers (
    OgrenciID INT NOT NULL,
    DersID INT NOT NULL,
    PRIMARY KEY (OgrenciID, DersID),
    FOREIGN KEY (OgrenciID) REFERENCES Ogrenci(OgrenciID),
    FOREIGN KEY (DersID) REFERENCES Ders(DersID)
);